[ROUTEAPI]
productos = http://187.210.65.46/api/ApiProductos/
doper = http://187.210.65.46/B2B/api/B2B/
auth = http://187.210.65.46/B2BIndustrias/api/Auth/
login = http://187.210.65.46/B2BIndustrias/api/Auth/login
authenticate = http://187.210.65.46/B2BIndustrias/api/Auth/authenticate
user-client-data = http://187.210.65.46/B2BIndustrias/api/Auth/user-client-data
user-client-accounts = http://187.210.65.46/B2BIndustrias/api/Auth/user-client-accounts
get-data-agent = http://187.210.65.46/B2BIndustrias/api/B2B/GetDataAgent
plantas-cliente-usuario = http://187.210.65.46/B2BIndustrias/api/B2B/plantas-cliente-usuario
b2b-search-products = http://187.210.65.46/B2BIndustrias/api/B2B/B2BSearchProducts
get-facturas-cliente = http://187.210.65.46/B2BIndustrias/api/b2b/get-facturas-cliente
get-datos-factura = http://187.210.65.46/B2BIndustrias/api/b2b/datos-factura
get-productos-factura = http://187.210.65.46/B2BIndustrias/api/b2b/get-productos-factura
get-facturas-totales = http://187.210.65.46/B2BIndustrias/api/b2b/get-factura-totales
crear-formulario-cliente = http://187.210.65.46/B2BIndustrias/api/b2b/crear-formulario-cliente
b2b-single-product = http://187.210.65.46/B2BIndustrias/api/b2b/B2BSingleProduct
get-cxc-cliente = http://187.210.65.46/B2BIndustrias/api/B2B/get-cxc-cliente
crear-solicitud-acceso = http://187.210.65.46/B2BIndustrias/api/Forms/crear-solicitud-acceso
crear-solicitud-acceso = http://187.210.65.46/B2BIndustrias/api/Forms/crear-solicitud-acceso
create-carrito = http://187.210.65.46/B2BIndustrias/api/Carrito/create-carrito
insert-item-carrito-estesi = http://187.210.65.46/B2BIndustrias/api/Carrito/insert-item-carrito-estesi
get-carrito = http://187.210.65.46/B2BIndustrias/api/Carrito/get-carrito
update-cantidad-item-carrito = http://187.210.65.46/B2BIndustrias/api/Carrito/update-cantidad-item-carrito
eliminar-item-carrito = http://187.210.65.46/B2BIndustrias/api/Carrito/eliminar-item-carrito
carrito-rapido = http://187.210.65.46/B2BIndustrias/CRM/CRMCreateCotizacion
exiros-search-products = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosSearchProducts
; exiros-search-products = https://localhost:44334/api/Exiros/ExirosSearchProducts
exiros-product-detail = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosProductDetail
; exiros-product-detail = https://localhost:44334/api/Exiros/ExirosProductDetail

exiros-get-categorias = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosGetCategorias
 exiros-get-compra = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosGetCompra
; exiros-get-compra = https://localhost:44334/api/Exiros/ExirosGetCompra
; exiros-estado-carrito = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosEstadoCarrito
;exiros-estado-carrito = https://localhost:44334/api/Exiros/ExirosEstadoCarrito
;exiros-cambiar-estado   = "https://localhost:44334/api/Exiros/ExirosCambiarEstadoCarrito"
exiros-estado-carrito = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosEstadoCarrito
exiros-cambiar-estado   = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosCambiarEstadoCarrito
get-cotizacion-crm = http://187.210.65.46/B2BIndustrias/api/Exiros/CRMGetCotizacion

exiros-Cotizacion-carrito = http://187.210.65.46/B2BIndustrias/api/Exiros/ExirosGuardarCompra


[APIKEY]
key = HjBp6NwKv5fKSQ9jsETAgFPgzLtWifHQtNlBVzQzGzz5XfOe3bTDrfRtaeaVtmtv
X-API-KEY = DeKCdWPmSqaAwFNVnUWZbnvtJyKJDUqEcXwCaXfSTaEBGYhXTdcbwtwCZNrXbcfm

[OCI]
; Credenciales mínimas permitidas para el login vía OCI (tester)
; TODO: mover estas credenciales a variables de entorno/secret manager para producción.
username = mersolsureste
password = "p}VTUqI{7({R"

; http://187.210.65.46/B2BIndustrias/api/Auth/login

; [ROUTEAPI]
; productos = http://187.210.65.46/api/ApiProductos/
; doper = http://187.210.65.46/B2B/api/B2B/
; auth = https://localhost:44334/api/Auth/
; login = https://localhost:44334/api/Auth/login
; authenticate = https://localhost:44334/api/Auth/authenticate 
; user-client-data = https://localhost:44334/Api/Auth/user-client-data
; user-client-accounts = https://localhost:44334/Api/Auth/user-client-accounts
; get-data-agent = https://localhost:44334/Api/B2B/GetDataAgent
; plantas-cliente-usuario = https://localhost:44334/Api/B2B/plantas-cliente-usuario
; b2b-search-products = https://localhost:44334/Api/B2B/B2BSearchProducts
; get-facturas-cliente = https://localhost:44334/api/b2b/get-facturas-cliente
; get-datos-factura = https://localhost:44334/api/b2b/datos-factura
; get-productos-factura = https://localhost:44334/api/b2b/get-productos-factura
; get-facturas-totales = https://localhost:44334/api/b2b/get-factura-totales
; crear-formulario-cliente = https://localhost:44334/api/b2b/crear-formulario-cliente
; b2b-single-product = https://localhost:44334/api/b2b/B2BSingleProduct
; get-cxc-cliente = https://localhost:44334/api/B2B/get-cxc-cliente
; crear-solicitud-acceso = https://localhost:44334/api/Forms/crear-solicitud-acceso
; create-carrito = https://localhost:44334/api/Carrito/create-carrito
; insert-item-carrito-estesi = https://localhost:44334/api/Carrito/insert-item-carrito-estesi
; get-carrito = https://localhost:44334/api/Carrito/get-carrito
; update-cantidad-item-carrito = https://localhost:44334/api/Carrito/update-cantidad-item-carrito
; eliminar-item-carrito = https://localhost:44334/api/Carrito/eliminar-item-carrito
; carrito-rapido = https://localhost:44334/api/CRM/CRMCreateCotizacion
; exiros-search-products = https://localhost:44334/api/Exiros/ExirosSearchProducts
; exiros-product-detail = https://localhost:44334/api/Exiros/ExirosProductDetail
; exiros-get-categorias = https://localhost:44334/api/Exiros/ExirosGetCategorias
; [APIKEY]
; key = HjBp6NwKv5fKSQ9jsETAgFPgzLtWifHQtNlBVzQzGzz5XfOe3bTDrfRtaeaVtmtv
; X-API-KEY = DeKCdWPmSqaAwFNVnUWZbnvtJyKJDUqEcXwCaXfSTaEBGYhXTdcbwtwCZNrXbcfm